@extends('layouts.app')
@section('title', 'Home')
@section('content')
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="hero d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-4">
                    {{-- <img src="{{ asset('img/QHI.png') }}" class="img-fluid" alt=""> --}}
                    <h2 data-aos="fade-up">Quickway Holdings, Inc.</h2>
                    <blockquote data-aos="fade-up" data-aos-delay="100">
                        <p>Empower your wealth with our dynamic holding company. Invest with confidence in our expertly
                            crafted portfolio of diverse investments, securing consistent returns and financial freedom.

                        </p>
                    </blockquote>
                    <div class="d-flex" data-aos="fade-up" data-aos-delay="200">
                        <a href="{{ route('about-us') }}" class="btn-get-started">Get Started</a>
                        {{-- <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ"
                        class="glightbox btn-watch-video d-flex align-items-center"><i
                            class="bi bi-play-circle"></i><span>Watch Video</span></a> --}}
                    </div>

                </div>
            </div>
        </div>
    </section><!-- End Hero Section -->
    <!-- ======= Why Choose Us Section ======= -->
    <section id="why-us" class="why-us">
        <div class="container" data-aos="fade-up">

            <div class="section-header">
                <h2>WHO ARE WE</h2>
            </div>
            <div class="row g-0" data-aos="fade-up" data-aos-delay="200">
                <div class="col-xl-5 img-bg" style="background-image: url('{{ asset('img/bldg.png') }}')"></div>
                <div class="col-xl-7 slides  position-relative">
                    <div class="slides-1 swiper">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <div class="item">
                                    <h3 class="mb-3">Definition of Quickway Holdings, Inc</h3>
                                    {{-- <h4 class="mb-3">Optio reiciendis accusantium iusto architecto at quia minima maiores
                                        quidem, dolorum.</h4> --}}
                                    <p>A Quickway Holdings is a business entity that doesn't have any operational activities
                                        but instead, owns and controls other companies. The primary purpose of a holding
                                        company is to own assets, including stocks, bonds, and other securities, and to
                                        receive a portion of the income generated by the subsidiary companies.</p>
                                </div>
                            </div><!-- End slide item -->

                            <div class="swiper-slide">
                                <div class="item">
                                    <h3 class="mb-3">Role of Quickway Holdings, Inc in Corporate Structures</h3>
                                    {{-- <h4 class="mb-3">Amet cumque nam sed voluptas doloribus iusto. Dolorem eos aliquam
                                        quis.
                                    </h4> --}}
                                    <p>Quickway Holdings play an important role in corporate structures by allowing for the
                                        centralized control and management of multiple businesses. This can provide a number
                                        of benefits, including the ability to pool resources, reduce costs, and minimize
                                        risks. Additionally, Quickway Holdings can also serve as a means of protecting
                                        valuable assets and engaging in strategic business planning and decision-making.</p>
                                </div>
                            </div><!-- End slide item -->

                            <div class="swiper-slide">
                                <div class="item">
                                    <h3 class="mb-3">Formation of Quickway Holdings, Inc</h3>
                                    {{-- <h4 class="mb-3">Necessitatibus voluptatibus explicabo dolores a vitae voluptatum.
                                    </h4> --}}
                                    <p>In order to form a Quickway Holdings, a business owner or group of investors must
                                        first
                                        create a new legal entity, often in the form of a corporation. Once the holding
                                        company is established, it can then acquire ownership of other companies through a
                                        variety of methods, such as purchasing stock or acquiring debt. The subsidiary
                                        companies can then operate independently, with the Quickway Holdings serving as a
                                        means of overseeing and managing their operations.</p>
                                </div>
                            </div><!-- End slide item -->

                            <div class="swiper-slide">
                                <div class="item">
                                    <h3 class="mb-3">Overall</h3>
                                    {{-- <h4 class="mb-3">Tempora quos est ut quia adipisci ut voluptas. Deleniti laborum
                                        soluta
                                        nihil est. Eum similique neque autem ut.</h4> --}}
                                    <p> Quickway Holdings can provide a number of strategic and financial benefits
                                        for business owners and investors. However, it's important to note that there can
                                        also be drawbacks, including potential conflicts of interest, increased regulatory
                                        scrutiny, and the need for specialized knowledge and expertise in order to
                                        effectively manage the holdings. As such, it's important to carefully consider the
                                        pros and cons of forming a Quickway Holdings before making a decision.</p>
                                </div>
                            </div><!-- End slide item -->
                        </div>
                        <div class="swiper-pagination"></div>
                    </div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>

                </div>

            </div>

        </div>
    </section><!-- End Why Choose Us Section -->


@endsection
